In [4]:
import numpy as np

In [5]:
a = np.array([1,2, 4, 5])
print(a)

[1 2 4 5]


# La Notion de vue et de copie

In [6]:
a = np.array([1,2, 4, 5])
b = a[:3]
print(f"Ce tableau b ", b ," est une vue du tableau a. La prevue : b.base donne le tableau a = ", b.base, "\n si le tableau b était une copie alors b.base serait = à None" )
print(f"b étant une vue de a <=> la modification de b entraîne celle de a")
b[2] = 10
print(f"b[2] =  {b[2]} ,ainsi b ={b} ,b étant une vue de a, a est également modifié : {a}")

Ce tableau b  [1 2 4]  est une vue du tableau a. La prevue : b.base donne le tableau a =  [1 2 4 5] 
 si le tableau b était une copie alors b.base serait = à None
b étant une vue de a <=> la modification de b entraîne celle de a
b[2] =  10 ,ainsi b =[ 1  2 10] ,b étant une vue de a, a est également modifié : [ 1  2 10  5]


### Forcer un tableau à être une vue ou une copie

In [7]:
a = np.array([1,2, 4, 5])
print(f"Nous pouvons forcer un tableau beta à être une copie d'un tableau alpha, par l'instruction : beta = alpha.copy()")
b = a[:3].copy()
print(f"b.base = {b.base}")
print(f"Nous pouvons également forcer un tableau beta à être une vue d'un tableau alpha, par l'instruction : beta = alpha.view()")
print(f"b étant une copie de a <=> la modification de b n'entraîne pas celle de a")
b[2] = 15
print(f"b[2] =  {b[2]} ,ainsi b ={b} ,b étant une copie de a, a est n'est pas modifié : {a}")

Nous pouvons forcer un tableau beta à être une copie d'un tableau alpha, par l'instruction : beta = alpha.copy()
b.base = None
Nous pouvons également forcer un tableau beta à être une vue d'un tableau alpha, par l'instruction : beta = alpha.view()
b étant une copie de a <=> la modification de b n'entraîne pas celle de a
b[2] =  15 ,ainsi b =[ 1  2 15] ,b étant une copie de a, a est n'est pas modifié : [1 2 4 5]


# Les attributs de tableau

In [8]:
a = np.array([3, 5, 12, 18, 9, 52, 64, 9])
print(f"La dimension de a : {a} est a.ndim = {a.ndim} , la forme est a est a.shape = {a.shape} , le nombre d'élement de a est : a.size = {a.size}")
print(f"L'attribut dtype nous permet de connaître le type des élements qui constitue le tableau.  a.dtype = {a.dtype}")

La dimension de a : [ 3  5 12 18  9 52 64  9] est a.ndim = 1 , la forme est a est a.shape = (8,) , le nombre d'élement de a est : a.size = 8
L'attribut dtype nous permet de connaître le type des élements qui constitue le tableau.  a.dtype = int64


# Création de tableau de base avec arange, linspace, zeros, ones

In [9]:
print(f"la syntaxe est np.zeros(nombre_elements, dtype=type) : {np.zeros(4, dtype="int64")}")
print(f" {np.zeros(4)}")

print(f"la syntaxe est np.empty(nombre_elements, dtype=type) : {np.empty(4, dtype="int64")}")
print(f"{np.empty(4)}")

print(f"la syntaxe est np.ones(nombre_elements, dtype=type) : {np.ones(4)}")

print(f"la syntaxe est np.arange(nombre_elements, dtype=type) : {np.arange(6)}")

print(f"la syntaxe est np.linspace(nombre_debut, nombre_fin, num=nombres_elements_dans_le_tableau, dtype = type)")
print(f"{np.linspace(3, 6, num=5, dtype = type)}")

la syntaxe est np.zeros(nombre_elements, dtype=type) : [0 0 0 0]
 [0. 0. 0. 0.]
la syntaxe est np.empty(nombre_elements, dtype=type) : [0 0 0 0]
[0. 0. 0. 0.]
la syntaxe est np.ones(nombre_elements, dtype=type) : [1. 1. 1. 1.]
la syntaxe est np.arange(nombre_elements, dtype=type) : [0 1 2 3 4 5]
la syntaxe est np.linspace(nombre_debut, nombre_fin, num=nombres_elements_dans_le_tableau, dtype = type)
[3.0 3.75 4.5 5.25 6.0]


# Changer la forme d'un tableau
###   - sans modifier les données : reshape
###   - peut modifier les données : resize

In [10]:
a = np.zeros(6)
print(f"a = {a}")
print(f"Modifions la forme de a avec le reshape, nous allons remplir le nouveau tableau par ligne, donc a = {np.reshape(a, (2,3), order ="C")}")
print(f"Modifions la forme de a avec le reshape, nous allons remplir le nouveau tableau par colonne, donc a = {np.reshape(a, (2,3), order ="F")}")

b = np.ones(3)
print(f"b = {b}")
print(f"Modifions la forme de b avec le resize, ici nous n'avons pas d'ordre de remplissage du tableau, donc b = {np.resize(b, (2,3))}")

a = [0. 0. 0. 0. 0. 0.]
Modifions la forme de a avec le reshape, nous allons remplir le nouveau tableau par ligne, donc a = [[0. 0. 0.]
 [0. 0. 0.]]
Modifions la forme de a avec le reshape, nous allons remplir le nouveau tableau par colonne, donc a = [[0. 0. 0.]
 [0. 0. 0.]]
b = [1. 1. 1.]
Modifions la forme de b avec le resize, ici nous n'avons pas d'ordre de remplissage du tableau, donc b = [[1. 1. 1.]
 [1. 1. 1.]]


# Tableau de structure

In [11]:
tpe = [("nom", "<U10"), ("prénom","<U10"), ("age", "int64")]
valeurs = [("ncho", "boni marie", 15), ("aka", "mouchia jocelyne", 21), ("doh", "marie colombe", 8), ("angbore", "emmanuel", 16)]
tab_struc = np.array(valeurs, dtype = tpe)
print(f"Voici le tableau structuré : {tab_struc}")

Voici le tableau structuré : [('ncho', 'boni marie', 15) ('aka', 'mouchia jo', 21)
 ('doh', 'marie colo',  8) ('angbore', 'emmanuel', 16)]


### Faire le tri avec np.sort()

In [12]:
tab_struc = np.array([("ncho", "boni marie dominique", 15), ("aka", "marie", 21), ("doh", "marie", 8), ("angbore", "emmanuel", 16)], [("nom", "<U10"), ("prénom","<U10"), ("age", "int64")])
print(f"le tableau trié par défaut : \n {np.sort(tab_struc)}")
print(f"\n")
print(f"le tableau en sens inverse : \n {np.sort(tab_struc)[::-1]}")
print(f"\n")
print(f" Tri du tableau par ordre alphabétique de prénom  : \n {np.sort(tab_struc, order=["prénom"], kind="mergesort")}")
print(f"\n")
print(f" Tri du tableau par ordre alphabétique de prénom, s'il y a égalité entre deux prénom alors tri par age : \n {np.sort(tab_struc, order=["prénom", "age"], kind="mergesort")}")
print(f"\n")
print(f" Tri le tableau par ordre alphabétique inverse des prénoms, s'il y a égalité entre deux prénoms, fais le tri suivant l'âge et par ordre décroissant  : \n {np.sort(tab_struc, order=["prénom", "age"], kind="mergesort")[::-1]}")
print(f"\n")

le tableau trié par défaut : 
 [('aka', 'marie', 21) ('angbore', 'emmanuel', 16) ('doh', 'marie',  8)
 ('ncho', 'boni marie', 15)]


le tableau en sens inverse : 
 [('ncho', 'boni marie', 15) ('doh', 'marie',  8)
 ('angbore', 'emmanuel', 16) ('aka', 'marie', 21)]


 Tri du tableau par ordre alphabétique de prénom  : 
 [('ncho', 'boni marie', 15) ('angbore', 'emmanuel', 16)
 ('aka', 'marie', 21) ('doh', 'marie',  8)]


 Tri du tableau par ordre alphabétique de prénom, s'il y a égalité entre deux prénom alors tri par age : 
 [('ncho', 'boni marie', 15) ('angbore', 'emmanuel', 16)
 ('doh', 'marie',  8) ('aka', 'marie', 21)]


 Tri le tableau par ordre alphabétique inverse des prénoms, s'il y a égalité entre deux prénoms, fais le tri suivant l'âge et par ordre décroissant  : 
 [('aka', 'marie', 21) ('doh', 'marie',  8) ('angbore', 'emmanuel', 16)
 ('ncho', 'boni marie', 15)]




## Changer la dimension d'un tableau existant en ajoutant un nouvel axe avec newaxis et expand_dims

#### newaxis

In [13]:
a = np.array([3, 5, 12, 18, 9, 52, 64, 9])
print(f" a = {a}")
print(f"a.shape = {a.shape} \n")
b = a[np.newaxis, :]
print(b.base)
print(f"b : {b}")
print(f"b.shape : {b.shape}")

print("\n")

c = a[:, np.newaxis]
print(c.base)
print(f"c : {c}")
print(f"c.shape : {c.shape} \n")

d = c[np.newaxis, :]
print(f"ajouter un troisième axe à c. Ainsi d = : {d}")
print(f"d.shape : {d.shape} \n")

 a = [ 3  5 12 18  9 52 64  9]
a.shape = (8,) 

[ 3  5 12 18  9 52 64  9]
b : [[ 3  5 12 18  9 52 64  9]]
b.shape : (1, 8)


[ 3  5 12 18  9 52 64  9]
c : [[ 3]
 [ 5]
 [12]
 [18]
 [ 9]
 [52]
 [64]
 [ 9]]
c.shape : (8, 1) 

ajouter un troisième axe à c. Ainsi d = : [[[ 3]
  [ 5]
  [12]
  [18]
  [ 9]
  [52]
  [64]
  [ 9]]]
d.shape : (1, 8, 1) 



#### expand_dims

In [14]:
a = np.array([3, 5, 12, 18, 9, 52, 64, 9])
print(f" a = {a}")
print(f"a.shape = {a.shape} \n")
b = np.expand_dims(a, axis = 1)
print(f" b = {b}")
print(f" b.shape = {b.shape}")

print(f"\n")

c = np.expand_dims(a, axis = 0)
print(f" c = {c}")
print(f" c.shape = {c.shape} \n")

e = c[:, np.newaxis]
print(f"ajouter un troisième axe à c. Ainsi e = : {e}")
print(f"d.shape : {e.shape} \n")

 a = [ 3  5 12 18  9 52 64  9]
a.shape = (8,) 

 b = [[ 3]
 [ 5]
 [12]
 [18]
 [ 9]
 [52]
 [64]
 [ 9]]
 b.shape = (8, 1)


 c = [[ 3  5 12 18  9 52 64  9]]
 c.shape = (1, 8) 

ajouter un troisième axe à c. Ainsi e = : [[[ 3  5 12 18  9 52 64  9]]]
d.shape : (1, 1, 8) 



## Sélectionner certains éléments dans un tableau numpy

In [15]:
my_tab = np.array([[1, 4, 6, 8],[11, 42, 65, 87]])
my_index = (my_tab > 5)
print(f"les élements supérieurs à 5 de notre tableau sont :{my_tab[my_index]}")

les élements supérieurs à 5 de notre tableau sont :[ 6  8 11 42 65 87]


In [16]:
my_tab = np.array([[1, 4, 6, 8],[11, 42, 65, 87]])
my_elements = (my_tab > 5) & (my_tab <= 60)
print(f"les élements supérieurs à 5 et inférieurs à 60 :{my_tab[my_index]}")

les élements supérieurs à 5 et inférieurs à 60 :[ 6  8 11 42 65 87]


In [17]:
my_tab = np.array([[1, 4, 6, 8],[11, 42, 65, 87]])
my_index = np.nonzero((my_tab > 5) & (my_tab <= 60))
print(f"les élements supérieurs à 5 et inférieurs à 60 : \n {my_index}")

les élements supérieurs à 5 et inférieurs à 60 : 
 (array([0, 0, 1, 1]), array([2, 3, 0, 1]))


## Apllatir un tableau multidimensionnel avec flatten() et ravel()

In [95]:
my_tab = np.array([[1, 4, 6, 8],[11, 42, 65, 87]])
tab_applatir_flatten = my_tab.flatten()
tab_applatir_ravel = my_tab.ravel()
print(f"Applatissons avec flatten le tableau : \n {my_tab}  \n ce qui donne : my_tab.flatten {tab_applatir_flatten.flatten()}, cette table est une copie car tab_applatir_flatten.base = {tab_applatir_flatten.base} ")
print("\n")
print(f"Applatissons avec flatten le tableau : \n {my_tab}  \n ce qui donne : my_tab.ravel {tab_applatir_flatten.ravel()}, cette table est une vue (référence) car tab_applatir_ravel.base = {tab_applatir_ravel.base} ")

Applatissons avec flatten le tableau : 
 [[ 1  4  6  8]
 [11 42 65 87]]  
 ce qui donne : my_tab.flatten [ 1  4  6  8 11 42 65 87], cette table est une copie car tab_applatir_flatten.base = None 


Applatissons avec flatten le tableau : 
 [[ 1  4  6  8]
 [11 42 65 87]]  
 ce qui donne : my_tab.ravel [ 1  4  6  8 11 42 65 87], cette table est une vue (référence) car tab_applatir_ravel.base = [[ 1  4  6  8]
 [11 42 65 87]] 


# La concaténation

#### - Pour les tableaux à 1 dimension c-i-e le shape de ce tableau est sous la forme : shape(nombre,)

In [18]:
a = np.array([1, 3, 5, 8])
b = np.array([13, 2, 56, 90])
print(f" la concatenation de a de forme {a.shape} et de b de forme {b.shape} donne : {np.concatenate((a,b))}")

print(f"\n")

a = np.array([1, 3, 5, 8])
b = np.array([13, 2, 56, 90, 23, 30, 11])
print(f" la concatenation de a de forme {a.shape} et de b de forme {b.shape} donne : {np.concatenate((a,b))}")

print(f"\n")

print(f" la concatenation de a de forme {a.shape} et de b de forme {b.shape} donne : {np.concatenate((a,b), axis = 0)}")

 la concatenation de a de forme (4,) et de b de forme (4,) donne : [ 1  3  5  8 13  2 56 90]


 la concatenation de a de forme (4,) et de b de forme (7,) donne : [ 1  3  5  8 13  2 56 90 23 30 11]


 la concatenation de a de forme (4,) et de b de forme (7,) donne : [ 1  3  5  8 13  2 56 90 23 30 11]


###### NB : la concatenation entre deux tableaux de dimension 1, ne peut pas se faire sur l'axis 1

#### - Pour les tableaux à 2 dimension c-i-e le shape de ce tableau est sous la forme : shape(nombre,nombre)

#####  NB : pour les tableaux à 2 dimensions, la concaténation peut se faire sur l'axis 0 comme sur l'axis 1.  à condition que nb_colonne_tab1 = nb_colonne_tab2 et nb_ligne_tab1 = nb_ligne_tab2 

In [19]:
tab_1 = np.array([[1, 3, 5, 8], [23, 56, 2, 80]])
tab_2 = np.array([[2, 4, 6], [24, 57, 3]])
tab_12 = np.concatenate((tab_1, tab_2), axis = 1)
print(f"la concaténation suivant la colonne de\n {tab_1} \n et de \n {tab_1} \n donne : \n {tab_12}")

la concaténation suivant la colonne de
 [[ 1  3  5  8]
 [23 56  2 80]] 
 et de 
 [[ 1  3  5  8]
 [23 56  2 80]] 
 donne : 
 [[ 1  3  5  8  2  4  6]
 [23 56  2 80 24 57  3]]


In [20]:
tab_1 = np.array([[1, 3, 5], [23, 56, 2]])
tab_2 = np.array([[2, 4, 6], [24, 57, 3], [79, 24, 8]])
tab_12 = np.concatenate((tab_1, tab_2), axis = 0)
print(f"la concaténation suivant la colonne de\n {tab_1} \n et de \n {tab_1} \n donne : \n {tab_12}")

la concaténation suivant la colonne de
 [[ 1  3  5]
 [23 56  2]] 
 et de 
 [[ 1  3  5]
 [23 56  2]] 
 donne : 
 [[ 1  3  5]
 [23 56  2]
 [ 2  4  6]
 [24 57  3]
 [79 24  8]]


### Empilement avec vstack (empilement verticale) et hstack (empilement horizontale)

In [ ]:
tab_1 = np.array([1, 3, 5])
tab_2 = np.array([23, 56, 2])
tab_12 = np.vstack ([tab_1, tab_2])
print(f"empilement vertical de tab_1 de dimension : {tab_1.ndim} et de tab_2 de dimension : {tab_2.ndim} donne : \n {tab_12}")

empilement verticale de tab_1 de dimension : 1 et de tab_2 de dimension : 1 donne : 
 [[ 1  3  5]
 [23 56  2]]


In [24]:
tab_1 = np.array([1, 3, 5])
tab_2 = np.array([23, 56, 2])
tab_12 = np.hstack ([tab_1, tab_2])
print(f"empilement horizontal de tab_1 de dimension : {tab_1.ndim} et de tab_2 de dimension : {tab_2.ndim} donne : \n {tab_12}")

empilement horizontal de tab_1 de dimension : 1 et de tab_2 de dimension : 1 donne : 
 [ 1  3  5 23 56  2]


### Le hsplit() : division d'un tableau en plusieurs tableaux

In [31]:
x = np.arange(1,25).reshape(2,12)
print(f"{x}")
print(f" Grâce à hsplit, nous avons divisé notre tableau en 3 partie égales : \n {np.hsplit(x, 3)}")

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
 Grâce à hsplit, nous avons divisé notre tableau en 3 partie égales : 
 [array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]


In [33]:
x = np.arange(1,25).reshape(2,12)
print(f"{x}")
print(f" Grâce à hsplit, nous avons divisé notre tableau à parir du 5ième élément, puis du 7ième élément, ce qui nous donne : \n {np.hsplit(x, (5, 7))}")

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
 Grâce à hsplit, nous avons divisé notre tableau à parir du 5ième élément, puis du 7ième élément, ce qui nous donne : 
 [array([[ 1,  2,  3,  4,  5],
       [13, 14, 15, 16, 17]]), array([[ 6,  7],
       [18, 19]]), array([[ 8,  9, 10, 11, 12],
       [20, 21, 22, 23, 24]])]


## La somme, la soustraction, la multiplication, la division  avec tablau a deux dimensions

In [52]:
tab_1 = np.array([[1, 3, 5], [23, 56, 2]])
tab_2 = np.array([[2, 4, 6], [24, 57, 3]])
tab_12a = tab_1 + tab_2
tab_12s = tab_1 - tab_2
tab_12m = tab_1 * tab_2
tab_12d = tab_1 / tab_2

print(f"la somme de table 1 de shape : {tab_1.shape} et de table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {tab_12a} de shape : {tab_12a.shape}")
print("\n")
print(f"la soustraction de table 1 de shape : {tab_1.shape} et de table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {tab_12s} de shape : {tab_12s.shape}")
print("\n")
print(f"la multiplication de table 1 de shape : {tab_1.shape} et de table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {tab_12m} de shape : {tab_12m.shape}")
print("\n")
print(f"la division de table 1 de shape : {tab_1.shape} par table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {tab_12d} de shape : {tab_12d.shape}")

la somme de table 1 de shape : (2, 3) et de table 2 de shape : (2, 3) donne la table ci-dessous : 
 [[  3   7  11]
 [ 47 113   5]] de shape : (2, 3)


la soustraction de table 1 de shape : (2, 3) et de table 2 de shape : (2, 3) donne la table ci-dessous : 
 [[-1 -1 -1]
 [-1 -1 -1]] de shape : (2, 3)


la multiplication de table 1 de shape : (2, 3) et de table 2 de shape : (2, 3) donne la table ci-dessous : 
 [[   2   12   30]
 [ 552 3192    6]] de shape : (2, 3)


la division de table 1 de shape : (2, 3) par table 2 de shape : (2, 3) donne la table ci-dessous : 
 [[0.5        0.75       0.83333333]
 [0.95833333 0.98245614 0.66666667]] de shape : (2, 3)


In [63]:
tab_1 = np.array([[1, 3, 5], [23, 56, 2]])
tab_2 = np.array([[2, 4, 6], [24, 57, 3]])

print(f"la somme de table 1 de shape : {tab_1.shape} et de table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {np.sum(tab_1 + tab_2)} de shape : {np.sum(tab_1 + tab_2).shape}")
print("\n")
print(f"la soustraction de table 1 de shape : {tab_1.shape} et de table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {np.sum(tab_1 - tab_2)} de shape : {np.sum(tab_1 - tab_2).shape}")
print("\n")
print(f"la multiplication de table 1 de shape : {tab_1.shape} et de table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {np.sum(tab_1 * tab_2)} de shape : {np.sum(tab_1 * tab_2).shape}")

print(f"la division de table 1 de shape : {tab_1.shape} et de table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {np.sum(tab_1 / tab_2)} de shape : {np.sum(tab_1 * tab_2).shape}")
print("\n")
print("\n")
print(f"la somme des éléments par ligne de table 1 de shape : {tab_1.shape} donne : \n {tab_1.sum(axis=0)} de shape : {tab_1.sum(axis=0).shape}")
print(f"la somme des éléments par ligne de table 1 de shape : {tab_1.shape} donne : \n {np.sum(tab_1, axis=0)} de shape : {np.sum(tab_1, axis=0).shape}")
print("\n")
print(f"la somme des éléments par colonne de table 1 de shape : {tab_1.shape} donne : \n {tab_1.sum(axis=1)} de shape : {tab_1.sum(axis=1).shape}")
print(f"la somme des éléments par colonne de table 1 de shape : {tab_1.shape} donne : \n {np.sum(tab_1, axis=1)} de shape : {np.sum(tab_1, axis=1).shape}")

la somme de table 1 de shape : (2, 3) et de table 2 de shape : (2, 3) donne la table ci-dessous : 
 186 de shape : ()


la soustraction de table 1 de shape : (2, 3) et de table 2 de shape : (2, 3) donne la table ci-dessous : 
 -6 de shape : ()


la multiplication de table 1 de shape : (2, 3) et de table 2 de shape : (2, 3) donne la table ci-dessous : 
 3794 de shape : ()
la division de table 1 de shape : (2, 3) et de table 2 de shape : (2, 3) donne la table ci-dessous : 
 4.6907894736842115 de shape : ()




la somme des éléments par ligne de table 1 de shape : (2, 3) donne : 
 [24 59  7] de shape : (3,)
la somme des éléments par ligne de table 1 de shape : (2, 3) donne : 
 [24 59  7] de shape : (3,)


la somme des éléments par colonne de table 1 de shape : (2, 3) donne : 
 [ 9 81] de shape : (2,)
la somme des éléments par colonne de table 1 de shape : (2, 3) donne : 
 [ 9 81] de shape : (2,)


### La somme, la soustraction, la multiplication, la division  avec tablau a une dimension

In [ ]:
tab_1 = np.array([1, 3, 5])
tab_2 = np.array([2, 4, 6])
tab_12a = tab_1 + tab_2
tab_12s = tab_1 - tab_2
tab_12m = tab_1 * tab_2
tab_12d = tab_1 / tab_2

print(f"la somme de table 1 de shape : {tab_1.shape} et de table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {tab_12a} de shape : {tab_12a.shape}")
print("\n")
print(f"la soustraction de table 1 de shape : {tab_1.shape} et de table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {tab_12s} de shape : {tab_12s.shape}")
print("\n")
print(f"la multiplication de table 1 de shape : {tab_1.shape} et de table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {tab_12m} de shape : {tab_12m.shape}")
print("\n")
print(f"la division de table 1 de shape : {tab_1.shape} par table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {tab_12d} de shape : {tab_12d.shape}")


la somme de table 1 de shape : (3,) et de table 2 de shape : (3,) donne la table ci-dessous : 
 [ 3  7 11] de shape : (3,)


la soustraction de table 1 de shape : (3,) et de table 2 de shape : (3,) donne la table ci-dessous : 
 [-1 -1 -1] de shape : (3,)


la multiplication de table 1 de shape : (3,) et de table 2 de shape : (3,) donne la table ci-dessous : 
 [ 2 12 30] de shape : (3,)


la division de table 1 de shape : (3,) par table 2 de shape : (3,) donne la table ci-dessous : 
 [0.5        0.75       0.83333333] de shape : (3,)


In [ ]:
tab_1 = np.array([1, 3, 5])
tab_2 = np.array([2, 4, 6])

print(f"la somme de table 1 de shape : {tab_1.shape} et de table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {np.sum(tab_1 + tab_2)} de shape : {np.sum(tab_1 + tab_2).shape}")
print("\n")
print(f"la soustraction de table 1 de shape : {tab_1.shape} et de table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {np.sum(tab_1 - tab_2)} de shape : {np.sum(tab_1 - tab_2).shape}")
print("\n")
print(f"la multiplication de table 1 de shape : {tab_1.shape} et de table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {np.sum(tab_1 * tab_2)} de shape : {np.sum(tab_1 * tab_2).shape}")
print("\n")
print(f"la division de table 1 de shape : {tab_1.shape} et de table 2 de shape : {tab_2.shape} donne la table ci-dessous : \n {np.sum(tab_1 / tab_2)} de shape : {np.sum(tab_1 * tab_2).shape}")

print("\n")
print("\n")
print(f"la somme des éléments de table 1 de shape : {tab_1.shape} donne : \n {tab_1.sum()} de shape : {tab_1.sum().shape}")
print(f"la somme des éléments de table 1 de shape : {tab_1.shape} donne : \n {np.sum(tab_1)} de shape : {np.sum(tab_1).shape}")
print("\n")
# error print(f"la somme des éléments de table 1 de shape : {tab_1.shape} donne : \n {np.sum(tab_1, axis = 1)} de shape : {np.sum(tab_1).shape}")
print(f"la somme des éléments de table 1 de shape : {tab_1.shape} donne : \n {np.sum(tab_1, axis = 0)} de shape : {np.sum(tab_1).shape}")

la somme de table 1 de shape : (3,) et de table 2 de shape : (3,) donne la table ci-dessous : 
 21 de shape : ()


la soustraction de table 1 de shape : (3,) et de table 2 de shape : (3,) donne la table ci-dessous : 
 -3 de shape : ()


la multiplication de table 1 de shape : (3,) et de table 2 de shape : (3,) donne la table ci-dessous : 
 44 de shape : ()


la division de table 1 de shape : (3,) et de table 2 de shape : (3,) donne la table ci-dessous : 
 2.0833333333333335 de shape : ()




la somme des éléments de table 1 de shape : (3,) donne : 
 9 de shape : ()
la somme des éléments de table 1 de shape : (3,) donne : 
 9 de shape : ()


la somme des éléments de table 1 de shape : (3,) donne : 
 9 de shape : ()


### La multiplication matricielle

In [ ]:
tab_1 = np.array([[4, 5, 6], [1, 2, 3], [4, 5, 6]])
tab_2 = np.array([[1, 2, 3], [1, 2, 3]])
tab_12_st_manner = tab_1.dot(tab_1)
tab_12_snd_manner = tab_1.dot(tab_1)
print(f"la multiplication matricielle de tab_1 de shape {tab_1.shape} et de tab_2 de shape {tab_2.shape} donne : \n {tab_12_st_manner}")
print(f"la multiplication matricielle de tab_1 de shape {tab_1.shape} et de tab_2 de shape {tab_2.shape} donne : \n {tab_12_snd_manner}")
print("\n")
print(f"NB : le nombre de colonne de la première table est égale au nombre de ligne de la seconde table")

la multiplication matricielle de tab_1 de shape (3, 3) et de tab_2 de shape (2, 3) donne : 
 [[45 60 75]
 [18 24 30]
 [45 60 75]]
la multiplication matricielle de tab_1 de shape (3, 3) et de tab_2 de shape (2, 3) donne : 
 [[45 60 75]
 [18 24 30]
 [45 60 75]]
NB : le nombre de colonne de la première table est égale au nombre de ligne de la seconde table


## Le min, max dans un tableau à deux dimension

In [72]:
tab_1 =np.array([[4, 5, 6], [1, 2, 3]])
print(f"tab_1.max() donne le plus grand nombre du tableau qui est : {tab_1.max()}")
print(f"tab_2.min() donne le plus petit nombre du tableau qui est : {tab_1.min()}")
print("\n")
print(f"tab_1.max(axis = 1) donne le plus grand nombre de chaque colonne du tableau qui est : {tab_1.max(axis = 1)}")
print(f"tab_1.max(axis = 0) donne le plus grand nombre de chaque ligne du tableau qui est : {tab_1.max(axis = 0)}")
print("\n")
print(f"tab_1.min(axis = 1) donne le plus petit nombre de chaque colonne du tableau qui est : {tab_1.min(axis = 1)}")
print(f"tab_1.min(axis = 0) donne le plus petit nombre de chaque ligne du tableau qui est : {tab_1.min(axis = 0)}")

tab_1.max() donne le plus grand nombre du tableau qui est : 6
tab_2.min() donne le plus petit nombre du tableau qui est : 1


tab_1.max(axis = 1) donne le plus grand nombre de chaque colonne du tableau qui est : [6 3]
tab_1.max(axis = 0) donne le plus grand nombre de chaque ligne du tableau qui est : [4 5 6]


tab_1.min(axis = 1) donne le plus petit nombre de chaque colonne du tableau qui est : [4 1]
tab_1.min(axis = 0) donne le plus petit nombre de chaque ligne du tableau qui est : [1 2 3]


## Le Broadcasting

### L'on peut procéder à l'addition, la soustraction, la multiplication et la division entre deux tableaux si :
##### - ces deux tableaux ont la même forme : même dimension.
##### - l'un des tableaux est de dimension 1 et de même nombre de dolonne que l'autre tableau qui est de dimension supérieure à 1.
##### - l'un est un scalaire et l'autre un tableau.

In [87]:
tab1 = np.array([1,1,1])
tab2 = np.array([[1,2,3],[1,2,3]])
tab_sum = tab1 + tab2
tab_produit = tab1 * tab2
tab_division = tab1 / tab2
tab1_sum_by_scalaire, tab2_sum_by_scalaire = tab1 + 2, tab2 + 2
# error ne prends pas le produit matricielle en compte tab_produit_matricielle = tab1.dot(tab2)

print(f"{tab_sum}")
print(f"{tab_produit}")
print(f"{tab_division}")
#print(f"{tab_produit_matricielle}")
print(f"{tab1_sum_by_scalaire} et \n {tab2_sum_by_scalaire}")

[[2 3 4]
 [2 3 4]]
[[1 2 3]
 [1 2 3]]
[[1.         0.5        0.33333333]
 [1.         0.5        0.33333333]]
[3 3 3] et 
 [[3 4 5]
 [3 4 5]]


#### Tableau dont les nombres sont générés de manière aléatoire entre un intervalle précis et de shape spécifié

In [90]:
rng = np.random.default_rng()
print(rng.integers(5, size=(2,3)))

print("\n")

print(rng.integers(5, size=(2,2,3)))

[[4 0 4]
 [4 2 4]]


[[[3 3 1]
  [3 1 1]]

 [[3 2 4]
  [3 2 2]]]


### Quels sont les nombre qui ne se répète pas dans mon tableau ? Donnez les index de ces nombres là

In [91]:
nbdef = np.array([1,2,4,4,8,1,5,5,12])
print(np.unique(nbdef))
print(np.unique(nbdef, return_index = True))

[ 1  2  4  5  8 12]
(array([ 1,  2,  4,  5,  8, 12]), array([0, 1, 2, 6, 4, 8]))


## Inverser un tableau avec np.flip()

In [104]:
tab_fdim = np.array([1,2,4,4,8,1,5,5,12])
print(np.flip(tab_fdim))
tab_sdim = np.array([[4, 5, 6], [1, 2, 3]])
print("\n")
print(np.flip(tab_sdim))
print("\n")
print(f"Inverser uniquemment les colonnes d'un tableau à 2 dimensions")
print(np.flip(tab_sdim, axis = 1))


print("\n")
print(f"Inverser uniquemment les lignes d'un tableau à 2 dimensions")
print(np.flip(tab_sdim, axis = 0))


print("\n")
print(f"Inverser uniquemment la première colonne d'un tableau à 2 dimensions")
invcolonneindex = np.array([[4, 5, 6], [1, 2, 3]])
invcolonneindex[:,0] = np.flip(invcolonneindex[:,0])
print(invcolonneindex)


print("\n")
print(f"Inverser uniquemment la ligne d'index 1 d'un tableau à 2 dimensions")
invligneindex = np.array([[4, 5, 6], [1, 2, 3]])
invligneindex[1] = np.flip(invligneindex[1])
print(invligneindex)

[12  5  5  1  8  4  4  2  1]


[[3 2 1]
 [6 5 4]]


Inverser uniquemment les colonnes d'un tableau à 2 dimensions
[[6 5 4]
 [3 2 1]]


Inverser uniquemment les lignes d'un tableau à 2 dimensions
[[1 2 3]
 [4 5 6]]


Inverser uniquemment la première colonne d'un tableau à 2 dimensions
[[1 5 6]
 [4 2 3]]


Inverser uniquemment la ligne d'index 1 d'un tableau à 2 dimensions
[[4 5 6]
 [3 2 1]]


### Transposé d'un tableau

In [ ]:
tab = np.array([[4, 5, 6], [1, 2, 3]])
print(f"la transposé du tableau tab : \n {tab} \n peut s'écrire avec tab.T : \n {tab.T} \n ou bien avec tab.transpose() : \n {tab.transpose()}")

la transposé du tableau : 
 [[4 5 6]
 [1 2 3]] 
 peut s'écrire avec tab.T : 
 [[4 1]
 [5 2]
 [6 3]] 
 ou bien avec tab.transpose() : 
 [[4 1]
 [5 2]
 [6 3]]
