# Revision pandas

In [35]:
import pandas as pd
import numpy as np

### création d'un dataframe

In [62]:
df_first = pd.DataFrame(
    {
    "Nom" : ["Ncho", "Boni" , "Marie"],
    "Classe" : [ "SRIT2B", "M2SIGL",    "SIGL1"],
    "anEtude" : [5 ,10 , 21]
}
)
print(f"Voici mon dataframe créé à la main : \n  {df_first}")
print("\n")
print(f"NB : Chaque colonne de df_first est un dataframe Series.")
print(f"\nTrouves le type de chaque colonne de df_first ainsi que le type de df_first lui-même : \n{df_first.dtypes}")

Voici mon dataframe créé à la main : 
       Nom  Classe  anEtude
0   Ncho  SRIT2B        5
1   Boni  M2SIGL       10
2  Marie   SIGL1       21


NB : Chaque colonne de df_first est un dataframe Series.

Trouves le type de chaque colonne de df_first ainsi que le type de df_first lui-même : 
Nom        object
Classe     object
anEtude     int64
dtype: object


In [17]:
serie_anEtude = df_first['anEtude']
print(f"Voici ce que j'obtiens (un dataframe Series) en sélectionnant la colonne anEtude de mon dataframe df_first : \n {serie_anEtude}")

Voici ce que j'obtiens (un dataframe Series) en sélectionnant la colonne anEtude de mon dataframe df_first : 
 0     5
1    10
2    21
Name: anEtude, dtype: int64


In [18]:
df_first_age = pd.Series(
    [25, 27, 28], name = "Age"
)
print(f"Je viens de créer un dataframe Series avec pandas.Series : \n {df_first_age}")

Je viens de créer un dataframe Series avec pandas.Series : 
 0    25
1    27
2    28
Name: Age, dtype: int64


## Faire quelque chose avec un dataframe series

In [20]:
print(f"{df_first_age.max()}")
print(f"{serie_anEtude.max()}")

28
21


## Faire quelque chose avec un dataframe

In [25]:
print(f"Utilisons la fonction describe() pour une description mathématique des colonnes numérique du dataframe \n {df_first.describe()}")
print("\n")
print(f"Utilisons la fonction describe(include = all) pour une description mathématique de toute les colonnes numérique du dataframe \n {df_first.describe(include = 'all')}")
print("\n")
print(f"Utilisons la fonction info() pour une description globale (Types des colonnes, valeurs non nulles, et mémoire utilisée.) \n {df_first.info()}")

Utilisons la fonction describe() pour une description mathématique des colonnes numérique du dataframe 
          anEtude
count   3.000000
mean   12.000000
std     8.185353
min     5.000000
25%     7.500000
50%    10.000000
75%    15.500000
max    21.000000


Utilisons la fonction describe(include = all) pour une description mathématique de toute les colonnes numérique du dataframe 
          Nom  Classe    anEtude
count      3       3   3.000000
unique     3       3        NaN
top     Ncho  SRIT2B        NaN
freq       1       1        NaN
mean     NaN     NaN  12.000000
std      NaN     NaN   8.185353
min      NaN     NaN   5.000000
25%      NaN     NaN   7.500000
50%      NaN     NaN  10.000000
75%      NaN     NaN  15.500000
max      NaN     NaN  21.000000


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Nom      3 non-null      object
 1   Classe   3 

## Création d'un dataframe avec données d'un tableau numpy, index, titre de colonne. 

In [42]:
my_index = pd.date_range("20230501", periods = 6)
print(f"Voici ce qui nous servira d'index : \n {my_index}")
print("\n")
my_col_title = pd.Series(list("ABCD"))
print(f"Voici les titres de mes colonnes : \n {my_col_title}")
print("\n")
data_np = np.random.random((6, 4))
print(f"Je crée maintenant un tableau numpy de 6 ligne et 4 colonne. Les valeurs de ce tableau sont aléatoires : \n {data_np}")
print("\n")
print("\n")
print(f"le dataframe sera créé maintenant. Le voilà : \n {pd.DataFrame(data_np, index = my_index, columns = my_col_title)}")

Voici ce qui nous servira d'index : 
 DatetimeIndex(['2023-05-01', '2023-05-02', '2023-05-03', '2023-05-04',
               '2023-05-05', '2023-05-06'],
              dtype='datetime64[ns]', freq='D')


Voici les titres de mes colonnes : 
 0    A
1    B
2    C
3    D
dtype: object


Je crée maintenant un tableau numpy de 6 ligne et 4 colonne. Les valeurs de ce tableau sont aléatoires : 
 [[0.10469197 0.77060478 0.96596189 0.33333229]
 [0.47649456 0.31274525 0.4627996  0.08847427]
 [0.21683361 0.25163129 0.78285443 0.97786024]
 [0.3576007  0.21090961 0.62079499 0.72662667]
 [0.17512354 0.80566363 0.19159495 0.63143419]
 [0.80666361 0.85659649 0.19107867 0.02340033]]




le dataframe sera créé maintenant. Le voilà : 
                    A         B         C         D
2023-05-01  0.104692  0.770605  0.965962  0.333332
2023-05-02  0.476495  0.312745  0.462800  0.088474
2023-05-03  0.216834  0.251631  0.782854  0.977860
2023-05-04  0.357601  0.210910  0.620795  0.726627
2023-05-05  0.17512

## Autre manière de créer un dataframe : par un dictionnaire d'objet

In [65]:
df_by_dict_objet = pd.DataFrame({
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["testA", "trainA", "testA", "trainB"]),
        "F": "foo",

})
print(df_by_dict_objet)

print(f"\n Utilisons le dtypes : \n{df_by_dict_objet.dtypes}")

     A          B    C  D       E    F
0  1.0 2013-01-02  1.0  3   testA  foo
1  1.0 2013-01-02  1.0  3  trainA  foo
2  1.0 2013-01-02  1.0  3   testA  foo
3  1.0 2013-01-02  1.0  3  trainB  foo

 Utilisons le dtypes : 
A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object


## Affichage

#### Afficher les premiers et les derniers éléments, les index, les colonnes, la transposé

In [ ]:
df_by_dict_objet = pd.DataFrame({
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["testA", "trainA", "testB", "trainB"]),
        "F": "foo",

})
print(f" Par défaut, df.head() affiche les 5 premiers éléments, ici nous passons 2 en paramètre pour afficher les 2 premiers : \n {df_by_dict_objet.head(2)}")

print("\n")
print(f" Par défaut, df.tail() affiche les 5 derniers éléments, ici nous passons 2 en paramètre pour afficher les 2 derniers : \n {df_by_dict_objet.head(2)}")
print("\n")
print(f"les index du dataframe sont : \n {df_by_dict_objet.index}")
print("\n")
print(f"les colonnes du dataframe sont : \n {df_by_dict_objet.columns}")
print("\n")
print(f"les index du dataframe sont : \n {df_by_dict_objet.index}")
print("\n")
print(f"les index du dataframe sont : \n {df_by_dict_objet.index}")
print("\n")
print(f"Donne moi la transposé de ton DataFrame : \n {df_by_dict_objet.T}")

 Par défaut, df.head() affiche les 5 premiers éléments, ici nous passons 2 en paramètre pour afficher les 2 premiers : 
      A          B    C  D       E    F
0  1.0 2013-01-02  1.0  3   testA  foo
1  1.0 2013-01-02  1.0  3  trainA  foo


 Par défaut, df.tail() affiche les 5 derniers éléments, ici nous passons 2 en paramètre pour afficher les 2 derniers : 
      A          B    C  D       E    F
0  1.0 2013-01-02  1.0  3   testA  foo
1  1.0 2013-01-02  1.0  3  trainA  foo


les index du dataframe sont : 
 Index([0, 1, 2, 3], dtype='int64')


les colonnes du dataframe sont : 
 Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


les index du dataframe sont : 
 Index([0, 1, 2, 3], dtype='int64')


les index du dataframe sont : 
 Index([0, 1, 2, 3], dtype='int64')


Donne moi la transposé de ton DataFrma : 
                      0                    1                    2  \
A                  1.0                  1.0                  1.0   
B  2013-01-02 00:00:00  2013-01-02 00:00:00

### Transformer le DataFrame en un tableau array numpy
NB : cette transformation est obligatoire, afin de pouvoir sélectionner par index les colonnes de se dataframe 

In [68]:
print(df_by_dict_objet.to_numpy())


[[1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'testA' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'trainA' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'testB' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'trainB' 'foo']]


## Tri du dataframe par axe ou par valeurs

### Tri du datafrme par axe

### Tri du dataframe par valeurs

## Sélection du dataframe